name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for code coverage
      run: |
        cd src 
        chmod +777 ./testNetCoreWin.bat 
        ./testNetCoreWin.bat
        ls -lh
        cp -r  ./coveragereport/* ../docs/
        rm -R ./coveragereport/
        ls -lh ../docs/coveragereport/
        ls -lh 
