name: GenerateCodeCoverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for code coverage
      run: |
        cd src 
        chmod +777 ./testNetCoreWin.bat 
        ./testNetCoreWin.bat
        ls -lh
        echo 'copy'
        cp -r  ./coveragereport/* ../docs/coveragereport/
        rm -R ./coveragereport/
        echo 'in docs/coveragereport'
        ls -lh ../docs/coveragereport/
        echo 'here'
        ls -lh 
 
 
    - name: Verify pkg
      run: |
        ls -lh src/
        ls -lh src/pkg/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: HealthCheckVersion
        path: src/pkg/*.s*nupkg

    - name: Delete pkg
      run: |
        cd src 
        rm -R ./pkg/
    
    - name: run commit
      run: |         
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git status
        git commit -m "generate code coverage" -a --allow-empty
      #shell: cmd
           
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
